[versions]
# build tools
java = "21"
jacoco = "0.8.14"

[libraries]
# build tools
gradle-nexus-publish = { module = "io.github.gradle-nexus:publish-plugin", version = "2.0.0" }
# dependencies
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.2-1" }
quark-eventbus = { module = "com.coditory.quark:quark-eventbus", version = "0.0.6" }
# test dependencies
spock-core = { module = "org.spockframework:spock-core", version = "2.4-M6-groovy-4.0" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.21" }
jsonassert = { module = "org.skyscreamer:jsonassert", version = "1.5.3" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher", version = "6.0.1" }